[workspace]
resolver = "2"
members = ["cli",
    "scan_core",
]

[workspace.dependencies]
tokio = { version="1.48.0", features=["full"] }
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
